"""
Supabase Service - Database operations for AiContent table
Handles all CRUD operations for math questions in Supabase

FIXED ISSUES:
- Issue #1: Uses 'id' primary key for updates/deletes instead of Question_Number
- Issue #2: Removed Question_Number parameter - database sequence handles it
- Issue #3: Added question_type column support with validation
"""
import os
from typing import List, Dict, Optional, Any
from datetime import datetime
from supabase import create_client, Client


class SupabaseService:
    """
    Service class for managing AiContent table in Supabase.
    Provides methods for creating, reading, updating, and deleting records.
    """
    
    def __init__(self, url: str = None, key: str = None):
        """
        Initialize the Supabase client.
        
        Args:
            url: Supabase project URL (defaults to SUPABASE_URL env var)
            key: Supabase API key (defaults to SUPABASE_KEY env var)
        """
        self.url = url or os.getenv("SUPABASE_URL")
        self.key = key or os.getenv("SUPABASE_KEY")
        
        if not self.url or not self.key:
            raise ValueError("Supabase URL and KEY are required. Set SUPABASE_URL and SUPABASE_KEY environment variables.")
        
        self.client: Client = create_client(self.url, self.key)
        self.table_name = "AiContent"
        self.valid_question_types = ['MCQ', 'Fill-in-the-Blank', 'Yes/No']
    
    def add_row(
        self,
        subject: str,
        subtopic: str,
        question: str,
        solution: str,
        final_answer: str,
        question_type: str  # NEW REQUIRED PARAMETER
    ) -> Dict[str, Any]:
        """
        Add a new row to the AiContent table.
        
        Args:
            subject: Subject area (e.g., "Mathematics")
            subtopic: Specific subtopic (e.g., "Algebra")
            question: The question text
            solution: Step-by-step solution
            final_answer: The final answer
            question_type: Type of question - must be 'MCQ', 'Fill-in-the-Blank', or 'Yes/No'
            
        Returns:
            Dictionary containing the inserted record
            
        Raises:
            ValueError: If question_type is invalid
            Exception: If insertion fails
            
        Note:
            Question_Number is auto-generated by database sequence
        """
        # Validate question_type
        if question_type not in self.valid_question_types:
            raise ValueError(
                f"Invalid question_type: '{question_type}'. "
                f"Must be one of {self.valid_question_types}"
            )
        
        try:
            data = {
                "Subject": subject,
                "Subtopic": subtopic,
                "Question": question,
                "Solution": solution,
                "Final_answer": final_answer,
                "question_type": question_type  # NEW FIELD
                # Question_Number will be auto-generated by database sequence
                # created_at will be auto-generated by Supabase
            }
            
            response = self.client.table(self.table_name).insert(data).execute()
            if response.data:
                question_number = response.data[0].get('Question_Number', 'N/A')
                row_id = response.data[0].get('id', 'N/A')
                print(f"✓ Successfully added {question_type} question #{question_number} (id: {row_id})")
                return response.data[0]
            return {}
            
        except Exception as e:
            print(f"✗ Error adding row: {str(e)}")
            raise
    
    def add_rows_batch(self, rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Add multiple rows to the AiContent table at once.
        
        Args:
            rows: List of dictionaries containing question data
                  Each dict should have: Subject, Subtopic, Question, 
                  Solution, Final_answer, question_type
                  Question_Number will be auto-generated
            
        Returns:
            List of inserted records
            
        Raises:
            ValueError: If any question_type is invalid
            Exception: If batch insertion fails
        """
        # Validate all question_types before insertion
        for idx, row in enumerate(rows):
            qt = row.get('question_type')
            if not qt or qt not in self.valid_question_types:
                raise ValueError(
                    f"Invalid question_type in row {idx}: '{qt}'. "
                    f"Must be one of {self.valid_question_types}"
                )
        
        try:
            response = self.client.table(self.table_name).insert(rows).execute()
            print(f"✓ Successfully added {len(rows)} questions")
            return response.data
            
        except Exception as e:
            print(f"✗ Error adding batch: {str(e)}")
            raise
    
    def fetch_all_rows(self) -> List[Dict[str, Any]]:
        """
        Fetch all rows from the AiContent table.
        
        Returns:
            List of all records
        """
        try:
            response = self.client.table(self.table_name).select("*").execute()
            print(f"✓ Fetched {len(response.data)} rows")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching all rows: {str(e)}")
            raise
    
    def fetch_row_by_id(self, row_id: int) -> Optional[Dict[str, Any]]:
        """
        Fetch a single row by its id (primary key).
        
        Args:
            row_id: The id (primary key) of the row to fetch
            
        Returns:
            Dictionary containing the record, or None if not found
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("id", row_id).execute()
            
            if response.data:
                print(f"✓ Fetched row with id {row_id}")
                return response.data[0]
            else:
                print(f"✗ No row found with id {row_id}")
                return None
                
        except Exception as e:
            print(f"✗ Error fetching row by id: {str(e)}")
            raise
    
    def fetch_row_by_question_number(self, question_number: int) -> Optional[Dict[str, Any]]:
        """
        Fetch a single row by its Question_Number.
        
        Args:
            question_number: The Question_Number of the row to fetch
            
        Returns:
            Dictionary containing the record, or None if not found
            
        Note:
            This method is kept for backward compatibility.
            For updates/deletes, use the id-based methods instead.
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Question_Number", question_number).execute()
            
            if response.data:
                print(f"✓ Fetched row with Question_Number {question_number}")
                return response.data[0]
            else:
                print(f"✗ No row found with Question_Number {question_number}")
                return None
                
        except Exception as e:
            print(f"✗ Error fetching row by Question_Number: {str(e)}")
            raise
    
    def fetch_rows_by_subject(self, subject: str) -> List[Dict[str, Any]]:
        """
        Fetch all rows for a specific subject.
        
        Args:
            subject: Subject to filter by
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Subject", subject).execute()
            print(f"✓ Fetched {len(response.data)} rows for subject: {subject}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by subject: {str(e)}")
            raise
    
    def fetch_rows_by_subtopic(self, subtopic: str) -> List[Dict[str, Any]]:
        """
        Fetch all rows for a specific subtopic.
        
        Args:
            subtopic: Subtopic to filter by
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Subtopic", subtopic).execute()
            print(f"✓ Fetched {len(response.data)} rows for subtopic: {subtopic}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by subtopic: {str(e)}")
            raise
    
    def fetch_rows_by_question_type(self, question_type: str) -> List[Dict[str, Any]]:
        """
        Fetch all rows for a specific question type.
        
        Args:
            question_type: Question type to filter by ('MCQ', 'Fill-in-the-Blank', 'Yes/No')
            
        Returns:
            List of matching records
            
        Raises:
            ValueError: If question_type is invalid
        """
        if question_type not in self.valid_question_types:
            raise ValueError(
                f"Invalid question_type: '{question_type}'. "
                f"Must be one of {self.valid_question_types}"
            )
        
        try:
            response = self.client.table(self.table_name).select("*").eq("question_type", question_type).execute()
            print(f"✓ Fetched {len(response.data)} rows for question_type: {question_type}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by question_type: {str(e)}")
            raise
    
    def fetch_rows_by_question_number(self, question_number: int) -> List[Dict[str, Any]]:
        """
        Fetch rows by question number.
        
        Args:
            question_number: Question number to filter by
            
        Returns:
            List of matching records
            
        Note:
            With UNIQUE constraint, this should return 0 or 1 record.
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Question_Number", question_number).execute()
            print(f"✓ Fetched {len(response.data)} rows for question number: {question_number}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by question number: {str(e)}")
            raise
    
    def fetch_rows_with_filter(self, filters: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Fetch rows with custom filters.
        
        Args:
            filters: Dictionary of column:value pairs to filter by
            
        Returns:
            List of matching records
            
        Example:
            filters = {"Subject": "Mathematics", "question_type": "MCQ"}
        """
        try:
            query = self.client.table(self.table_name).select("*")
            
            for column, value in filters.items():
                query = query.eq(column, value)
            
            response = query.execute()
            print(f"✓ Fetched {len(response.data)} rows with filters: {filters}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows with filters: {str(e)}")
            raise
    
    def update_row(self, row_id: int, updates: Dict[str, Any]) -> Dict[str, Any]:
        """
        Update an existing row by its id (primary key).
        
        FIXED: Now uses 'id' instead of 'Question_Number' for reliable updates.
        
        Args:
            row_id: The id (primary key) of the row to update
            updates: Dictionary of column:value pairs to update
            
        Returns:
            Updated record
            
        Raises:
            ValueError: If question_type in updates is invalid
            Exception: If update fails
            
        Example:
            updates = {"Solution": "New solution", "Final_answer": "42"}
            updates = {"question_type": "Fill-in-the-Blank"}
        """
        # Validate question_type if it's being updated
        if 'question_type' in updates:
            if updates['question_type'] not in self.valid_question_types:
                raise ValueError(
                    f"Invalid question_type: '{updates['question_type']}'. "
                    f"Must be one of {self.valid_question_types}"
                )
        
        try:
            response = self.client.table(self.table_name).update(updates).eq("id", row_id).execute()
            
            if response.data:
                print(f"✓ Successfully updated row with id {row_id}")
                return response.data[0]
            else:
                print(f"✗ No row found with id {row_id}")
                return {}
                
        except Exception as e:
            print(f"✗ Error updating row: {str(e)}")
            raise
    
    def delete_row(self, row_id: int) -> bool:
        """
        Delete a row by its id (primary key).
        
        FIXED: Now uses 'id' instead of 'Question_Number' for reliable deletes.
        
        Args:
            row_id: The id (primary key) of the row to delete
            
        Returns:
            True if deletion was successful
            
        Raises:
            Exception: If deletion fails
        """
        try:
            response = self.client.table(self.table_name).delete().eq("id", row_id).execute()
            print(f"✓ Successfully deleted row with id {row_id}")
            return True
            
        except Exception as e:
            print(f"✗ Error deleting row: {str(e)}")
            raise
    
    def delete_rows_by_subject(self, subject: str) -> bool:
        """
        Delete all rows for a specific subject.
        
        Args:
            subject: Subject to filter by
            
        Returns:
            True if deletion was successful
            
        Warning:
            This will delete ALL rows matching the subject!
        """
        try:
            response = self.client.table(self.table_name).delete().eq("Subject", subject).execute()
            print(f"✓ Successfully deleted rows for subject: {subject}")
            return True
            
        except Exception as e:
            print(f"✗ Error deleting rows by subject: {str(e)}")
            raise
    
    def count_rows(self) -> int:
        """
        Count total number of rows in the table.
        
        Returns:
            Total count of rows
        """
        try:
            response = self.client.table(self.table_name).select("*", count="exact").execute()
            count = response.count if hasattr(response, 'count') else len(response.data)
            print(f"✓ Total rows in table: {count}")
            return count
            
        except Exception as e:
            print(f"✗ Error counting rows: {str(e)}")
            raise
    
    def count_rows_by_question_type(self) -> Dict[str, int]:
        """
        Count rows grouped by question type.
        
        Returns:
            Dictionary mapping question_type to count
            
        Example:
            {"MCQ": 45, "Fill-in-the-Blank": 30, "Yes/No": 25}
        """
        try:
            counts = {}
            for qtype in self.valid_question_types:
                response = self.client.table(self.table_name).select("*", count="exact").eq("question_type", qtype).execute()
                count = response.count if hasattr(response, 'count') else len(response.data)
                counts[qtype] = count
            
            print(f"✓ Question type distribution: {counts}")
            return counts
            
        except Exception as e:
            print(f"✗ Error counting by question type: {str(e)}")
            raise
    
    def search_questions(self, search_term: str) -> List[Dict[str, Any]]:
        """
        Search for questions containing a specific term.
        
        Args:
            search_term: Term to search for in questions
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").ilike("Question", f"%{search_term}%").execute()
            print(f"✓ Found {len(response.data)} questions matching: {search_term}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error searching questions: {str(e)}")
            raise
    
    def get_latest_questions(self, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Get the most recently created questions.
        
        Args:
            limit: Maximum number of records to return
            
        Returns:
            List of latest records
        """
        try:
            response = (
                self.client.table(self.table_name)
                .select("*")
                .order("created_at", desc=True)
                .limit(limit)
                .execute()
            )
            print(f"✓ Fetched {len(response.data)} latest questions")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching latest questions: {str(e)}")
            raise


# Example usage and testing
if __name__ == "__main__":
    # Initialize the service
    try:
        db = SupabaseService()
        
        # Example 1: Add a single row (NO question_number parameter needed!)
        print("\n=== Example 1: Adding a single row ===")
        new_question = db.add_row(
            subject="Mathematics",
            subtopic="Algebra",
            question="Solve for x: 2x + 5 = 13",
            solution="Step 1: Subtract 5 from both sides\n2x = 8\nStep 2: Divide both sides by 2\nx = 4",
            final_answer="x = 4",
            question_type="Fill-in-the-Blank"  # NEW REQUIRED PARAMETER
        )
        print(f"Added: {new_question}")
        
        # Example 2: Fetch all rows
        print("\n=== Example 2: Fetching all rows ===")
        all_questions = db.fetch_all_rows()
        print(f"Total questions: {len(all_questions)}")
        
        # Example 3: Fetch by question type
        print("\n=== Example 3: Fetching by question type ===")
        mcq_questions = db.fetch_rows_by_question_type("MCQ")
        print(f"MCQ questions: {len(mcq_questions)}")
        
        # Example 4: Update using id (not Question_Number!)
        print("\n=== Example 4: Updating a row by id ===")
        if new_question and 'id' in new_question:
            updated = db.update_row(
                row_id=new_question['id'],
                updates={"question_type": "MCQ"}
            )
            print(f"Updated: {updated}")
        
        # Example 5: Count by question type
        print("\n=== Example 5: Count by question type ===")
        distribution = db.count_rows_by_question_type()
        
        # Example 6: Delete using id (not Question_Number!)
        print("\n=== Example 6: Deleting a row by id ===")
        if new_question and 'id' in new_question:
            db.delete_row(row_id=new_question['id'])
        
    except Exception as e:
        print(f"Error in example usage: {str(e)}")