"""
Configuration file for subjects and their related subtopics.
Add your subjects and subtopics here.
"""

# Dictionary mapping subjects to their subtopics
SUBJECTS_AND_SUBTOPICS = {
    "Algebra 1": [
        "Expressions - B.1 Write variable expressions",
        "Expressions - B.2 Evaluate variable expressions involving integers",
        "Expressions - B.3 Evaluate variable expressions involving rational numbers",
        "Expressions - B.4 Evaluate rational expressions",
        "Expressions - B.5 Properties of addition and multiplication",
        "Expressions - B.6 Distributive property",
        "Expressions - B.7 Simplify linear expressions using properties",
        "Expressions - B.8 Sort factors of variable expressions",
        "Expressions - B.9 Simplify variable expressions involving like terms and the distributive property",
        "Expressions - B.10 Identify equivalent linear expressions",
        # C. Solve linear equations
        "Solve linear equations - C.1 Write variable equations",
        "Solve linear equations - C.2 Does x satisfy the equation?",
        "Solve linear equations - C.3 Which x satisfies an equation?",
        "Solve linear equations - C.4 Properties of equality",
        "Solve linear equations - C.5 Identify equivalent equations",
        "Solve linear equations - C.6 Model and solve linear equations using algebra tiles",
        "Solve linear equations - C.7 Solve one-step linear equations",
        "Solve linear equations - C.8 Solve two-step linear equations",
        "Solve linear equations - C.9 Solve one-step and two-step linear equations: word problems",
        "Solve linear equations - C.10 Solve linear equations with variables on one side",
        "Solve linear equations - C.11 Consecutive integer problems",
        "Solve linear equations - C.12 Solve linear equations with variables on both sides",
        "Solve linear equations - C.13 Solve linear equations: mixed review",
        "Solve linear equations - C.14 Solve linear equations: complete the solution",
        "Solve linear equations - C.15 Find the number of solutions to a linear equation",
        "Solve linear equations - C.16 Create linear equations with no solutions or infinitely many solutions",
        "Solve linear equations - C.17 Solve linear equations with variables on both sides: word problems",
        "Solve linear equations - C.18 Rearrange multi-variable equations",
        # D. Geometry and measurement
        "Geometry and measurement - D.1 Area and perimeter: word problems",
        "Geometry and measurement - D.2 Volume",
        "Geometry and measurement - D.3 Surface area",
        "Geometry and measurement - D.4 Precision",
        "Geometry and measurement - D.5 Greatest possible error",
        "Geometry and measurement - D.6 Minimum and maximum area and volume",
        "Geometry and measurement - D.7 Percent error",
        "Geometry and measurement - D.8 Percent error: area and volume",
        # E. Problem solving with units
        "Problem solving with units - E.1 Scale drawings: word problems",
        "Problem solving with units - E.2 Convert rates and measurements: customary units",
        "Problem solving with units - E.3 Convert rates and measurements: metric units",
        "Problem solving with units - E.4 Unit prices with unit conversions",
        "Problem solving with units - E.5 Multi-step problems with unit conversions",
        "Problem solving with units - E.6 Rate of travel: word problems",
        "Problem solving with units - E.7 Weighted averages: word problems",
        # F. Solve linear inequalities
        "Solve linear inequalities - F.1 Graph inequalities",
        "Solve linear inequalities - F.2 Write inequalities from graphs",
        "Solve linear inequalities - F.3 Identify solutions to inequalities",
        "Solve linear inequalities - F.4 Solve one-step linear inequalities: addition and subtraction",
        "Solve linear inequalities - F.5 Solve one-step linear inequalities: multiplication and division",
        "Solve linear inequalities - F.6 Solve one-step linear inequalities",
        "Solve linear inequalities - F.7 Graph solutions to one-step linear inequalities",
        "Solve linear inequalities - F.8 Solve two-step linear inequalities",
        "Solve linear inequalities - F.9 Graph solutions to two-step linear inequalities",
        "Solve linear inequalities - F.10 Solve advanced linear inequalities",
        "Solve linear inequalities - F.11 Graph solutions to advanced linear inequalities",
        "Solve linear inequalities - F.12 Graph compound inequalities",
        "Solve linear inequalities - F.13 Write compound inequalities from graphs",
        "Solve linear inequalities - F.14 Solve compound inequalities",
        "Solve linear inequalities - F.15 Graph solutions to compound inequalities",
        # G. Sets
        "Sets - G.1 Sets, subsets, and complements",
        "Sets - G.2 Set-builder notation",
        "Sets - G.3 Interval notation",
        "Sets - G.4 Unions and intersections of sets",
        # H. Absolute value equations and inequalities
        "Absolute value equations and inequalities - H.1 Solve absolute value equations",
        "Absolute value equations and inequalities - H.2 Graph solutions to absolute value equations",
        "Absolute value equations and inequalities - H.3 Write absolute value equations from graphs",
        "Absolute value equations and inequalities - H.4 Solve absolute value inequalities",
        "Absolute value equations and inequalities - H.5 Graph solutions to absolute value inequalities",
        # I. Coordinate plane
        "Coordinate plane - I.1 Coordinate plane review",
        "Coordinate plane - I.2 Midpoint formula: find the midpoint",
        "Coordinate plane - I.3 Midpoint formula: find the endpoint",
        "Coordinate plane - I.4 Distance between two points",
        # J. Direct and inverse variation
        "Direct and inverse variation - J.1 Find the constant of variation",
        "Direct and inverse variation - J.2 Write direct variation equations",
        "Direct and inverse variation - J.3 Write and solve direct variation equations",
        "Direct and inverse variation - J.4 Identify direct variation and inverse variation",
        "Direct and inverse variation - J.5 Write inverse variation equations",
        "Direct and inverse variation - J.6 Write and solve inverse variation equations",
        # K. Slope
        "Slope - K.1 Find the slope of a graph",
        "Slope - K.2 Find the slope from two points",
        "Slope - K.3 Find the slope from a table",
        "Slope - K.4 Find a missing coordinate using slope",
        # L. Linear equations
        "Linear equations - L.1 Does (x, y) satisfy the linear equation?",
        "Linear equations - L.2 Relate the graph of a linear equation to its solutions",
        "Linear equations - L.3 Slope-intercept form: find the slope and y-intercept",
        "Linear equations - L.4 Slope-intercept form: graph an equation",
        "Linear equations - L.5 Slope-intercept form: write an equation from a graph",
        "Linear equations - L.6 Slope-intercept form: write an equation",
        "Linear equations - L.7 Slope-intercept form: write an equation from a table",
        "Linear equations - L.8 Linear equations: solve for y",
        "Linear equations - L.9 Write linear equations in standard form",
        "Linear equations - L.10 Standard form: find x- and y-intercepts",
        "Linear equations - L.11 Standard form: graph a line from an equation",
        "Linear equations - L.12 Equations of horizontal and vertical lines",
        "Linear equations - L.13 Graph a horizontal or vertical line",
        "Linear equations - L.14 Point-slope form: graph an equation",
        "Linear equations - L.15 Point-slope form: write an equation",
        "Linear equations - L.16 Point-slope form: write an equation from a graph",
        "Linear equations - L.17 Find the slope and intercepts from an equation",
        "Linear equations - L.18 Slopes of parallel and perpendicular lines",
        "Linear equations - L.19 Write an equation for a parallel or perpendicular line",
        # M. Function concepts
        "Function concepts - M.1 Relations: convert between tables, graphs, mappings, and lists of points",
        "Function concepts - M.2 Domain and range of relations",
        "Function concepts - M.3 Identify independent and dependent variables",
        "Function concepts - M.4 Identify functions",
        "Function concepts - M.5 Identify functions: vertical line test",
        "Function concepts - M.6 Find values using function graphs",
        "Function concepts - M.7 Evaluate a function",
        "Function concepts - M.8 Evaluate a function: plug in an expression",
        "Function concepts - M.9 Complete a function table from a graph",
        "Function concepts - M.10 Complete a function table from an equation",
        "Function concepts - M.11 Find solutions using a table",
        "Function concepts - M.12 Approximate solutions using a table",
        "Function concepts - M.13 Interpret functions using everyday language",
        "Function concepts - M.14 Identify graphs: word problems",
        "Function concepts - M.15 Rate of change: tables",
        "Function concepts - M.16 Rate of change: graphs",
        # N. Linear functions
        "Linear functions - N.1 Identify linear functions from graphs and equations",
        "Linear functions - N.2 Identify linear functions from tables",
        "Linear functions - N.3 Complete a table and graph a linear function",
        "Linear functions - N.4 Evaluate a linear function from its graph: word problems",
        "Linear functions - N.5 Rate of change of a linear function: tables",
        "Linear functions - N.6 Rate of change of a linear function: graphs",
        "Linear functions - N.7 Interpret the slope and y-intercept of a linear function",
        "Linear functions - N.8 Write a linear function: word problems",
        "Linear functions - N.9 Domain and range of linear functions: graphs",
        "Linear functions - N.10 Domain and range of linear functions: word problems",
        "Linear functions - N.11 Compare linear functions: graphs and equations",
        "Linear functions - N.12 Compare linear functions: tables, graphs, and equations",
        "Linear functions - N.13 Transformations of linear functions",
        # O. Systems of linear equations
        "Systems of linear equations - O.1 Is (x, y) a solution to the system of equations?",
        "Systems of linear equations - O.2 Solve a system of equations by graphing",
        "Systems of linear equations - O.3 Solve a system of equations by graphing: word problems",
        "Systems of linear equations - O.4 Find the number of solutions to a system of equations by graphing",
        "Systems of linear equations - O.5 Find the number of solutions to a system of equations",
        "Systems of linear equations - O.6 Classify a system of equations by graphing",
        "Systems of linear equations - O.7 Classify a system of equations",
        "Systems of linear equations - O.8 Solve a system of equations using substitution",
        "Systems of linear equations - O.9 Solve a system of equations using substitution: word problems",
        "Systems of linear equations - O.10 Solve a system of equations using elimination",
        "Systems of linear equations - O.11 Solve a system of equations using elimination: word problems",
        "Systems of linear equations - O.12 Solve a system of equations using augmented matrices",
        "Systems of linear equations - O.13 Solve a system of equations using augmented matrices: word problems",
        "Systems of linear equations - O.14 Solve a system of equations using any method",
        "Systems of linear equations - O.15 Solve a system of equations using any method: word problems",
        # P. Two-variable linear inequalities
        "Two-variable linear inequalities - P.1 Does (x, y) satisfy the inequality?",
        "Two-variable linear inequalities - P.2 Linear inequalities: solve for y",
        "Two-variable linear inequalities - P.3 Graph a two-variable linear inequality",
        "Two-variable linear inequalities - P.4 Write a linear inequality from a graph",
        "Two-variable linear inequalities - P.5 Write two-variable inequalities: word problems",
        "Two-variable linear inequalities - P.6 Is (x, y) a solution to the system of linear inequalities?",
        "Two-variable linear inequalities - P.7 Solve systems of linear inequalities by graphing",
        # Q. Piecewise-defined functions
        "Piecewise-defined functions - Q.1 Evaluate piecewise-defined functions",
        "Piecewise-defined functions - Q.2 Graph piecewise-defined functions",
        # R. Integer exponents
        "Integer exponents - R.1 Powers with integer bases",
        "Integer exponents - R.2 Powers with decimal and fractional bases",
        "Integer exponents - R.3 Negative exponents",
        "Integer exponents - R.4 Multiplication rule for exponents",
        "Integer exponents - R.5 Division rule for exponents",
        "Integer exponents - R.6 Power rule for exponents",
        "Integer exponents - R.7 Simplify exponential expressions using the multiplication rule",
        "Integer exponents - R.8 Simplify exponential expressions using the division rule",
        "Integer exponents - R.9 Simplify exponential expressions using the multiplication and division rules",
        "Integer exponents - R.10 Simplify exponential expressions using the power rule",
        "Integer exponents - R.11 Simplify exponential expressions using exponent rules",
        "Integer exponents - R.12 Evaluate expressions using exponent rules",
        "Integer exponents - R.13 Identify equivalent exponential expressions I",
        "Integer exponents - R.14 Identify equivalent exponential expressions II",
        # S. Rational exponents
        "Rational exponents - S.1 Evaluate integers raised to positive rational exponents",
        "Rational exponents - S.2 Evaluate integers raised to rational exponents",
        "Rational exponents - S.3 Multiplication with rational exponents",
        "Rational exponents - S.4 Division with rational exponents",
        "Rational exponents - S.5 Power rule with rational exponents",
        "Rational exponents - S.6 Simplify expressions involving rational exponents",
        # T. Scientific notation
        "Scientific notation - T.1 Convert between standard and scientific notation",
        "Scientific notation - T.2 Compare numbers written in scientific notation",
        "Scientific notation - T.3 Add and subtract numbers written in scientific notation",
        "Scientific notation - T.4 Multiply numbers written in scientific notation",
        "Scientific notation - T.5 Divide numbers written in scientific notation",
        # U. Sequences
        "Sequences - U.1 Identify arithmetic and geometric sequences",
        "Sequences - U.2 Arithmetic sequences",
        "Sequences - U.3 Geometric sequences",
        "Sequences - U.4 Evaluate variable expressions for number sequences",
        "Sequences - U.5 Evaluate recursive formulas for sequences",
        "Sequences - U.6 Identify a sequence as explicit or recursive",
        "Sequences - U.7 Write variable expressions for arithmetic sequences",
        "Sequences - U.8 Write variable expressions for geometric sequences",
        "Sequences - U.9 Write a formula for a recursive sequence",
        "Sequences - U.10 Convert a recursive formula to an explicit formula",
        "Sequences - U.11 Convert an explicit formula to a recursive formula",
        "Sequences - U.12 Sequences: mixed review",
        # V. Exponential functions
        "Exponential functions - V.1 Evaluate an exponential function",
        "Exponential functions - V.2 Graph exponential functions",
        "Exponential functions - V.3 Match exponential functions and graphs I",
        "Exponential functions - V.4 Match exponential functions and graphs II",
        "Exponential functions - V.5 Domain and range of exponential functions: graphs",
        "Exponential functions - V.6 Domain and range of exponential functions: equations",
        "Exponential functions - V.7 Write exponential functions from tables and graphs",
        "Exponential functions - V.8 Write exponential functions: word problems",
        "Exponential functions - V.9 Exponential growth and decay: word problems",
        "Exponential functions - V.10 Compound interest: word problems",
        # W. Polynomials
        "Polynomials - W.1 Polynomial vocabulary",
        "Polynomials - W.2 Model polynomials with algebra tiles",
        "Polynomials - W.3 Add and subtract polynomials using algebra tiles",
        "Polynomials - W.4 Add and subtract polynomials",
        "Polynomials - W.5 Add polynomials to find perimeter",
        "Polynomials - W.6 Multiply a polynomial by a monomial",
        "Polynomials - W.7 Multiply two binomials using algebra tiles",
        "Polynomials - W.8 Multiply two binomials",
        "Polynomials - W.9 Multiply two binomials: special cases",
        "Polynomials - W.10 Multiply polynomials using area models",
        "Polynomials - W.11 Multiply polynomials",
        "Polynomials - W.12 Multiply polynomials to find area",
        "Polynomials - W.13 Divide polynomials by monomials",
        "Polynomials - W.14 Divide polynomials using long division",
        # X. Factor polynomials
        "Factor polynomials - X.1 GCF of monomials",
        "Factor polynomials - X.2 LCM of monomials",
        "Factor polynomials - X.3 Factor out a monomial",
        "Factor polynomials - X.4 Factor quadratics using algebra tiles",
        "Factor polynomials - X.5 Factor quadratics with leading coefficient 1",
        "Factor polynomials - X.6 Factor quadratics with other leading coefficients",
        "Factor polynomials - X.7 Factor quadratics: special cases",
        "Factor polynomials - X.8 Factor by grouping",
        "Factor polynomials - X.9 Factor using a quadratic pattern",
        "Factor polynomials - X.10 Factor polynomials",
        # Y. Quadratic functions
        "Quadratic functions - Y.1 Characteristics of quadratic functions: graphs",
        "Quadratic functions - Y.2 Characteristics of quadratic functions: equations",
        "Quadratic functions - Y.3 Complete a function table: quadratic functions",
        "Quadratic functions - Y.4 Transformations of quadratic functions",
        "Quadratic functions - Y.5 Graph quadratic functions in vertex form",
        "Quadratic functions - Y.6 Write a quadratic function in vertex form",
        "Quadratic functions - Y.7 Graph quadratic functions in standard form",
        "Quadratic functions - Y.8 Match quadratic functions and graphs",
        "Quadratic functions - Y.9 Domain and range of quadratic functions: graphs",
        "Quadratic functions - Y.10 Domain and range of quadratic functions: equations",
        "Quadratic functions - Y.11 Write a quadratic function in vertex form from its vertex and another point",
        "Quadratic functions - Y.12 Write a quadratic function in factored form from its x-intercepts and another point",
        "Quadratic functions - Y.13 Write a quadratic function in standard form from its x-intercepts and another point",
        "Quadratic functions - Y.14 Interpret parts of quadratic expressions: word problems",
        # Z. Quadratic equations
        "Quadratic equations - Z.1 Solve a quadratic equation using square roots",
        "Quadratic equations - Z.2 Solve a quadratic equation using the zero product property",
        "Quadratic equations - Z.3 Solve a quadratic equation by factoring",
        "Quadratic equations - Z.4 Complete the square",
        "Quadratic equations - Z.5 Solve a quadratic equation by completing the square",
        "Quadratic equations - Z.6 Solve a quadratic equation using the quadratic formula",
        "Quadratic equations - Z.7 Solve quadratic equations: word problems",
        "Quadratic equations - Z.8 Using the discriminant",
        "Quadratic equations - Z.9 Solve a system of linear and quadratic equations by graphing",
        "Quadratic equations - Z.10 Solve a system of linear and quadratic equations",
        # AA. Linear, quadratic, and exponential functions
        "Linear, quadratic, and exponential functions - AA.1 Identify linear and exponential functions from graphs",
        "Linear, quadratic, and exponential functions - AA.2 Identify linear, quadratic, and exponential functions from graphs",
        "Linear, quadratic, and exponential functions - AA.3 Identify linear and exponential functions from tables",
        "Linear, quadratic, and exponential functions - AA.4 Identify linear, quadratic, and exponential functions from tables",
        "Linear, quadratic, and exponential functions - AA.5 Write linear and exponential functions: word problems",
        "Linear, quadratic, and exponential functions - AA.6 Write linear and exponential functions from tables",
        "Linear, quadratic, and exponential functions - AA.7 Write linear, quadratic, and exponential functions from tables",
        "Linear, quadratic, and exponential functions - AA.8 Linear functions over unit intervals",
        "Linear, quadratic, and exponential functions - AA.9 Exponential functions over unit intervals",
        "Linear, quadratic, and exponential functions - AA.10 Describe linear and exponential growth and decay",
        "Linear, quadratic, and exponential functions - AA.11 Compare linear and exponential growth",
        "Linear, quadratic, and exponential functions - AA.12 Compare linear, exponential, and quadratic growth",
        # BB. Absolute value functions
        "Absolute value functions - BB.1 Complete a function table: absolute value functions",
        "Absolute value functions - BB.2 Graph an absolute value function",
        "Absolute value functions - BB.3 Domain and range of absolute value functions: graphs",
        "Absolute value functions - BB.4 Domain and range of absolute value functions: equations",
        "Absolute value functions - BB.5 Transformations of absolute value functions: translations and reflections",
        "Absolute value functions - BB.6 Transformations of absolute value functions: translations, reflections, and dilations",
        # CC. Function operations
        "Function operations - CC.1 Add and subtract functions",
        "Function operations - CC.2 Multiply functions",
        "Function operations - CC.3 Find the inverse of a linear function",
        # DD. Function transformations
        "Function transformations - DD.1 Function transformation rules",
        "Function transformations - DD.2 Translations of functions",
        "Function transformations - DD.3 Reflections of functions",
        "Function transformations - DD.4 Dilations of functions",
        "Function transformations - DD.5 Transformations of functions",
        "Function transformations - DD.6 Describe function transformations",
        # EE. Radical expressions
        "Radical expressions - EE.1 Simplify radical expressions",
        "Radical expressions - EE.2 Simplify radical expressions with variables",
        "Radical expressions - EE.3 Simplify radical expressions involving fractions",
        "Radical expressions - EE.4 Multiply radical expressions",
        "Radical expressions - EE.5 Add and subtract radical expressions",
        "Radical expressions - EE.6 Simplify radical expressions using the distributive property",
        "Radical expressions - EE.7 Simplify radical expressions using conjugates",
        "Radical expressions - EE.8 Simplify radical expressions: mixed review",
        "Radical expressions - EE.9 Convert between rational exponents and radicals",
        # FF. Radical functions and equations
        "Radical functions and equations - FF.1 Evaluate square root functions",
        "Radical functions and equations - FF.2 Domain and range of square root functions: graphs",
        "Radical functions and equations - FF.3 Domain and range of square root functions: equations",
        "Radical functions and equations - FF.4 Graph square root functions",
        "Radical functions and equations - FF.5 Graph cube root functions",
        "Radical functions and equations - FF.6 Solve radical equations I",
        "Radical functions and equations - FF.7 Solve radical equations II",
        # GG. Rational functions and expressions
        "Rational functions and expressions - GG.1 Rational functions: asymptotes and excluded values",
        "Rational functions and expressions - GG.2 Simplify rational expressions",
        "Rational functions and expressions - GG.3 Multiply and divide rational expressions",
        "Rational functions and expressions - GG.4 Add and subtract rational expressions",
        "Rational functions and expressions - GG.5 Simplify mixed rational expressions",
        "Rational functions and expressions - GG.6 Solve rational equations",
        # HH. Data and graphs
        "Data and graphs - HH.1 Create line plots",
        "Data and graphs - HH.2 Interpret line plots",
        "Data and graphs - HH.3 Create histograms",
        "Data and graphs - HH.4 Interpret histograms",
        "Data and graphs - HH.5 Create bar graphs, line graphs, and histograms",
        "Data and graphs - HH.6 Interpret bar graphs, line graphs, and histograms",
        "Data and graphs - HH.7 Interpret circle graphs",
        "Data and graphs - HH.8 Interpret stem-and-leaf plots",
        "Data and graphs - HH.9 Box plots",
        "Data and graphs - HH.10 Interpret graphics I",
        "Data and graphs - HH.11 Interpret graphics II",
        # II. Single-variable statistics
        "Single-variable statistics - II.1 Identify biased samples",
        "Single-variable statistics - II.2 Mean, median, mode, and range",
        "Single-variable statistics - II.3 Calculate quartiles and interquartile range",
        "Single-variable statistics - II.4 Identify an outlier",
        "Single-variable statistics - II.5 Identify an outlier and describe the effect of removing it",
        "Single-variable statistics - II.6 Variance and standard deviation",
        "Single-variable statistics - II.7 Choose appropriate measures of center and variation",
        # JJ. Bivariate statistics
        "Bivariate statistics - JJ.1 Interpret a scatter plot",
        "Bivariate statistics - JJ.2 Outliers in scatter plots",
        "Bivariate statistics - JJ.3 Match correlation coefficients to scatter plots",
        "Bivariate statistics - JJ.4 Calculate correlation coefficients",
        "Bivariate statistics - JJ.5 Write equations for lines of best fit",
        "Bivariate statistics - JJ.6 Interpret lines of best fit: word problems",
        "Bivariate statistics - JJ.7 Find the equation of a regression line",
        "Bivariate statistics - JJ.8 Interpret regression lines",
        "Bivariate statistics - JJ.9 Analyze a regression line of a data set",
        "Bivariate statistics - JJ.10 Exponential regression",
        "Bivariate statistics - JJ.11 Correlation and causation",
        # KK. Probability
        "Probability - KK.1 Theoretical probability",
        "Probability - KK.2 Experimental probability",
        "Probability - KK.3 Find probabilities using two-way frequency tables",
        "Probability - KK.4 Find conditional probabilities using two-way frequency tables",
        "Probability - KK.5 Outcomes of compound events",
        "Probability - KK.6 Identify independent and dependent events",
        "Probability - KK.7 Probability of independent and dependent events",
        "Probability - KK.8 Counting principle",
        "Probability - KK.9 Permutations",
        "Probability - KK.10 Permutation and combination notation",
        # LL. Matrices
        "Matrices - LL.1 Matrix vocabulary",
        "Matrices - LL.2 Matrix operation rules",
        "Matrices - LL.3 Add and subtract matrices",
        "Matrices - LL.4 Multiply a matrix by a scalar",
        "Matrices - LL.5 Add and subtract scalar multiples of matrices",
        "Matrices - LL.6 Multiply two matrices",
        "Matrices - LL.7 Properties of matrices"
    ],
    "Geometry": [
        "Triangles",
        "Circles",
        "Polygons",
        "Area and Perimeter",
        "Volume and Surface Area",
        "Angles",
        "Parallel and Perpendicular Lines",
        "Transformations",
        "Coordinate Geometry",
        "Similarity and Congruence"
    ],
    "Trigonometry": [
        "Right Triangle Trigonometry",
        "Unit Circle",
        "Trigonometric Functions",
        "Trigonometric Identities",
        "Inverse Trigonometric Functions",
        "Trigonometric Equations",
        "Law of Sines",
        "Law of Cosines",
        "Graphs of Trigonometric Functions",
        "Applications of Trigonometry"
    ],
    "Calculus": [
        "Limits",
        "Derivatives",
        "Integration",
        "Applications of Derivatives",
        "Applications of Integration",
        "Differential Equations",
        "Series and Sequences",
        "Multivariable Calculus",
        "Vector Calculus",
        "Optimization"
    ],
    "Statistics & Probability": [
        "Descriptive Statistics",
        "Probability Basics",
        "Probability Distributions",
        "Normal Distribution",
        "Binomial Distribution",
        "Hypothesis Testing",
        "Confidence Intervals",
        "Correlation and Regression",
        "Sampling Methods",
        "Combinatorics"
    ],
    "Number Theory": [
        "Prime Numbers",
        "Divisibility",
        "Greatest Common Divisor (GCD)",
        "Least Common Multiple (LCM)",
        "Modular Arithmetic",
        "Diophantine Equations",
        "Perfect Numbers",
        "Fibonacci Sequence",
        "Integer Properties",
        "Factorization"
    ]
}

# Get list of all subjects (sorted alphabetically)
def get_subjects():
    """Return a sorted list of all available subjects."""
    return sorted(SUBJECTS_AND_SUBTOPICS.keys())

# Get subtopics for a specific subject
def get_subtopics(subject):
    """Return the list of subtopics for a given subject."""
    return SUBJECTS_AND_SUBTOPICS.get(subject, [])
