"""
Supabase Service - Database operations for AiContent table
Handles all CRUD operations for math questions in Supabase
"""
import os
from typing import List, Dict, Optional, Any
from datetime import datetime
from supabase import create_client, Client


class SupabaseService:
    """
    Service class for managing AiContent table in Supabase.
    Provides methods for creating, reading, updating, and deleting records.
    """
    
    def __init__(self, url: str = None, key: str = None):
        """
        Initialize the Supabase client.
        
        Args:
            url: Supabase project URL (defaults to SUPABASE_URL env var)
            key: Supabase API key (defaults to SUPABASE_KEY env var)
        """
        self.url = url or os.getenv("SUPABASE_URL")
        self.key = key or os.getenv("SUPABASE_KEY")
        
        if not self.url or not self.key:
            raise ValueError("Supabase URL and KEY are required. Set SUPABASE_URL and SUPABASE_KEY environment variables.")
        
        self.client: Client = create_client(self.url, self.key)
        self.table_name = "AiContent"
    
    def add_row(
        self,
        subject: str,
        subtopic: str,
        question: str,
        solution: str,
        final_answer: str,
        question_number: int
    ) -> Dict[str, Any]:
        """
        Add a new row to the AiContent table.
        
        Args:
            subject: Subject area (e.g., "Mathematics")
            subtopic: Specific subtopic (e.g., "Algebra")
            question: The question text
            solution: Step-by-step solution
            final_answer: The final answer
            question_number: Question number/identifier
            
        Returns:
            Dictionary containing the inserted record
            
        Raises:
            Exception: If insertion fails
        """
        try:
            data = {
                "Subject": subject,
                "Subtopic": subtopic,
                "Question": question,
                "Solution": solution,
                "Final_answer": final_answer,
                "Question_Number": question_number
                # created_at will be auto-generated by Supabase
            }
            
            response = self.client.table(self.table_name).insert(data).execute()
            print(f"✓ Successfully added question #{question_number}")
            return response.data[0] if response.data else {}
            
        except Exception as e:
            print(f"✗ Error adding row: {str(e)}")
            raise
    
    def add_rows_batch(self, rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Add multiple rows to the AiContent table at once.
        
        Args:
            rows: List of dictionaries containing question data
                  Each dict should have: Subject, Subtopic, Question, 
                  Solution, Final_answer, Question_Number
            
        Returns:
            List of inserted records
            
        Raises:
            Exception: If batch insertion fails
        """
        try:
            response = self.client.table(self.table_name).insert(rows).execute()
            print(f"✓ Successfully added {len(rows)} questions")
            return response.data
            
        except Exception as e:
            print(f"✗ Error adding batch: {str(e)}")
            raise
    
    def fetch_all_rows(self) -> List[Dict[str, Any]]:
        """
        Fetch all rows from the AiContent table.
        
        Returns:
            List of all records
        """
        try:
            response = self.client.table(self.table_name).select("*").execute()
            print(f"✓ Fetched {len(response.data)} rows")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching all rows: {str(e)}")
            raise
    
    def fetch_row_by_question_number(self, question_number: int) -> Optional[Dict[str, Any]]:
        """
        Fetch a single row by its Question_Number.
        
        Args:
            question_number: The Question_Number of the row to fetch
            
        Returns:
            Dictionary containing the record, or None if not found
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Question_Number", question_number).execute()
            
            if response.data:
                print(f"✓ Fetched row with Question_Number {question_number}")
                return response.data[0]
            else:
                print(f"✗ No row found with Question_Number {question_number}")
                return None
                
        except Exception as e:
            print(f"✗ Error fetching row by Question_Number: {str(e)}")
            raise
    
    def fetch_rows_by_subject(self, subject: str) -> List[Dict[str, Any]]:
        """
        Fetch all rows for a specific subject.
        
        Args:
            subject: Subject to filter by
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Subject", subject).execute()
            print(f"✓ Fetched {len(response.data)} rows for subject: {subject}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by subject: {str(e)}")
            raise
    
    def fetch_rows_by_subtopic(self, subtopic: str) -> List[Dict[str, Any]]:
        """
        Fetch all rows for a specific subtopic.
        
        Args:
            subtopic: Subtopic to filter by
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Subtopic", subtopic).execute()
            print(f"✓ Fetched {len(response.data)} rows for subtopic: {subtopic}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by subtopic: {str(e)}")
            raise
    
    def fetch_rows_by_question_number(self, question_number: int) -> List[Dict[str, Any]]:
        """
        Fetch rows by question number.
        
        Args:
            question_number: Question number to filter by
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").eq("Question_Number", question_number).execute()
            print(f"✓ Fetched {len(response.data)} rows for question number: {question_number}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows by question number: {str(e)}")
            raise
    
    def fetch_rows_with_filter(self, filters: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Fetch rows with custom filters.
        
        Args:
            filters: Dictionary of column:value pairs to filter by
            
        Returns:
            List of matching records
            
        Example:
            filters = {"Subject": "Mathematics", "Subtopic": "Algebra"}
        """
        try:
            query = self.client.table(self.table_name).select("*")
            
            for column, value in filters.items():
                query = query.eq(column, value)
            
            response = query.execute()
            print(f"✓ Fetched {len(response.data)} rows with filters: {filters}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching rows with filters: {str(e)}")
            raise
    
    def update_row(self, question_number: int, updates: Dict[str, Any]) -> Dict[str, Any]:
        """
        Update an existing row by Question_Number.
        
        Args:
            question_number: Question_Number of the row to update
            updates: Dictionary of column:value pairs to update
            
        Returns:
            Updated record
            
        Example:
            updates = {"Solution": "New solution", "Final_answer": "42"}
        """
        try:
            response = self.client.table(self.table_name).update(updates).eq("Question_Number", question_number).execute()
            
            if response.data:
                print(f"✓ Successfully updated row with Question_Number {question_number}")
                return response.data[0]
            else:
                print(f"✗ No row found with Question_Number {question_number}")
                return {}
                
        except Exception as e:
            print(f"✗ Error updating row: {str(e)}")
            raise
    
    def delete_row(self, question_number: int) -> bool:
        """
        Delete a row by Question_Number.
        
        Args:
            question_number: Question_Number of the row to delete
            
        Returns:
            True if deletion was successful
        """
        try:
            response = self.client.table(self.table_name).delete().eq("Question_Number", question_number).execute()
            print(f"✓ Successfully deleted row with Question_Number {question_number}")
            return True
            
        except Exception as e:
            print(f"✗ Error deleting row: {str(e)}")
            raise
    
    def delete_rows_by_subject(self, subject: str) -> bool:
        """
        Delete all rows for a specific subject.
        
        Args:
            subject: Subject to filter by
            
        Returns:
            True if deletion was successful
            
        Warning:
            This will delete ALL rows matching the subject!
        """
        try:
            response = self.client.table(self.table_name).delete().eq("Subject", subject).execute()
            print(f"✓ Successfully deleted rows for subject: {subject}")
            return True
            
        except Exception as e:
            print(f"✗ Error deleting rows by subject: {str(e)}")
            raise
    
    def count_rows(self) -> int:
        """
        Count total number of rows in the table.
        
        Returns:
            Total count of rows
        """
        try:
            response = self.client.table(self.table_name).select("*", count="exact").execute()
            count = response.count if hasattr(response, 'count') else len(response.data)
            print(f"✓ Total rows in table: {count}")
            return count
            
        except Exception as e:
            print(f"✗ Error counting rows: {str(e)}")
            raise
    
    def search_questions(self, search_term: str) -> List[Dict[str, Any]]:
        """
        Search for questions containing a specific term.
        
        Args:
            search_term: Term to search for in questions
            
        Returns:
            List of matching records
        """
        try:
            response = self.client.table(self.table_name).select("*").ilike("Question", f"%{search_term}%").execute()
            print(f"✓ Found {len(response.data)} questions matching: {search_term}")
            return response.data
            
        except Exception as e:
            print(f"✗ Error searching questions: {str(e)}")
            raise
    
    def get_latest_questions(self, limit: int = 10) -> List[Dict[str, Any]]:
        """
        Get the most recently created questions.
        
        Args:
            limit: Maximum number of records to return
            
        Returns:
            List of latest records
        """
        try:
            response = (
                self.client.table(self.table_name)
                .select("*")
                .order("created_at", desc=True)
                .limit(limit)
                .execute()
            )
            print(f"✓ Fetched {len(response.data)} latest questions")
            return response.data
            
        except Exception as e:
            print(f"✗ Error fetching latest questions: {str(e)}")
            raise


# Example usage and testing
if __name__ == "__main__":
    # Initialize the service
    try:
        db = SupabaseService()
        
        # Example 1: Add a single row
        print("\n=== Example 1: Adding a single row ===")
        new_question = db.add_row(
            subject="Mathematics",
            subtopic="Algebra",
            question="Solve for x: 2x + 5 = 13",
            solution="Step 1: Subtract 5 from both sides\n2x = 8\nStep 2: Divide both sides by 2\nx = 4",
            final_answer="x = 4",
            question_number=1
        )
        print(f"Added: {new_question}")
        
        # Example 2: Fetch all rows
        print("\n=== Example 2: Fetching all rows ===")
        all_questions = db.fetch_all_rows()
        print(f"Total questions: {len(all_questions)}")
        
        # Example 3: Fetch by subject
        print("\n=== Example 3: Fetching by subject ===")
        math_questions = db.fetch_rows_by_subject("Mathematics")
        
        # Example 4: Search questions
        print("\n=== Example 4: Searching questions ===")
        search_results = db.search_questions("solve")
        
        # Example 5: Get latest questions
        print("\n=== Example 5: Getting latest questions ===")
        latest = db.get_latest_questions(limit=5)
        
        # Example 6: Count rows
        print("\n=== Example 6: Counting rows ===")
        total = db.count_rows()
        
    except Exception as e:
        print(f"Error in example usage: {str(e)}")
